# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.CharField(default='', max_length=10)),
                ('pt', models.CharField(default='', max_length=10)),
                ('turn', models.CharField(default='000', max_length=4)),
                ('board', models.TextField(default='944448033330000000000000011110922228')),
            ],
        ),
    ]
