# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s1',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='s2',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn',
            field=models.CharField(default='00', max_length=3),
        ),
    ]
